version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - autoconf
    - automake
    - gcc
    - git
    - libtool
    - libyaml-dev
    - make
    - man
    - m4
  jobs:
    post_system_dependencies:
      - echo "USER=`user` HOME=${HOME}"
      - echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
      - git clone https://github.com/scott-guthridge/libvna.git
      - test -d "${HOME}/.local" || mkdir "${HOME}/.local"
      - |
        ( cd libvna &&
        ./bootstrap &&
        ./configure --prefix="${HOME}/.local" &&
        make -j12 install )
    post_install:
      - pip install .
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
