version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - sudo
  jobs:
    pre_system_dependencies:
      - .github/scripts/install-libvna.sh

sphinx:
  configuration: docs/source/conf.py
