version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - autoconf
    - automake
    - gcc
    - git
    - libtool
    - libyaml-dev
    - make
    - man
    - m4
  jobs:
    post_system_dependencies:
      - git clone https://github.com/scott-guthridge/libvna.git
      - |
        cd libvna &&
        ./bootstrap &&
        ./configure --prefix="${HOME}" &&
        make -j12 install
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: docs/requirements.txt
