[build-system]
requires = ["setuptools", "Cython", "numpy", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name         = "vna"
version      = "0.0.2"
description  = "Vector network analyzer calibration, load, store and convert"
authors      = [
    { name = "D Scott Guthridge", email = "scott_guthridge@rompromity.net" }
]
license = { file = "LICENSE" }
readme = { file = "README", content-type = "text/plain" }
requires-python = ">=3.7"

[project.urls]
repository = "https://github.com/scott-guthridge/python3-vna"

[project.optional-dependencies]
dev = ["pytest", "unittest"]

[tool.setuptools]
py-modules = ["_custom_build"]

[tool.setuptools.cmdclass]
build_py = "_custom_build.build_py"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
