#!/usr/bin/python3
import os
import requests
import subprocess
import sys

'''
Download the .deb packages from the latest release of libvna and
install them.
'''

url = 'https://api.github.com/repos/scott-guthridge/libvna/releases/latest'
try:
    response = requests.get(url)
    if response.status_code != 200:
        print(f'Status code: {response.status_code}')
    result = response.json()
    files = []
    for item in result['assets']:
        if 'browser_download_url' in item:
            value = item['browser_download_url']
            if value.endswith('.deb'):
                status = subprocess.run(['curl', '-L', '-O', value])
                if status.returncode != 0:
                    sys.exit(status.returncode)
                files.append('./' + os.path.basename(value))
    status = subprocess.run(['echo', 'apt-get', 'install', '-y'] +
                            files)
    if status.returncode != 0:
        sys.exit(status.returncode)
except Exception as e:
    print(f'Exception: {e}', file=sys.stderr)
    sys.exit(99)
